# Generated by Django 4.0.5 on 2022-06-06 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='casts',
            field=models.ManyToManyField(blank=True, null=True, to='movies.cast'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='genere',
            field=models.ManyToManyField(blank=True, null=True, to='movies.genere'),
        ),
    ]
