# Generated by Django 4.0.5 on 2022-06-06 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_alter_movie_casts_alter_movie_genere'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cast',
            old_name='age',
            new_name='cast_age',
        ),
        migrations.RenameField(
            model_name='cast',
            old_name='awards',
            new_name='cast_awards',
        ),
        migrations.RenameField(
            model_name='cast',
            old_name='name',
            new_name='cast_name',
        ),
    ]
