# Generated by Django 4.0.5 on 2022-06-07 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_rename_age_cast_cast_age_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='movie_name',
            new_name='movie_title',
        ),
    ]
