# Generated by Django 4.0.5 on 2022-06-07 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_rename_movie_name_movie_movie_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='release_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
